# Generated by Django 5.1.1 on 2024-09-20 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0002_alter_game_created_by_alter_rating_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='player',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='picture',
            name='action_pic',
            field=models.ImageField(null=True, upload_to='actionimages'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='raterapi.game'),
        ),
    ]
